log:
  path: "./debug.log"
  mode: ["file", "stream", "journal"]
  logger: {}
  level: "DEBUG"
run:
  simulation: False
i2c_mapping:
  raspberry:
    address: 0x10
    bus: 1
  esp_sensors:
    address: 0x20
    bus: 2
  esp_steppers:
    address: 0x08
    bus: 3