log:
  path: "./debug.log"
  module: ["file", "stream", "journal"]
  logger: {}
  level: "DEBUG"
simulation:
  run : True
  size : 400
i2c_mapping:
  raspberry:
    address: 0x10
    bus: 1
  esp_sensors:
    address: 0x20
    bus: 2
  esp_steppers:
    address: 0x08
    bus: 3
dimension:
  robot:
    radius : 0.3
  map:
    width : 3000
    height : 2000
