log:
  - name: i2c
    path: "log/debug.log"
    level: "DEBUG"
run:
  simulation: False
i2c_mapping:
  raspberry:
    address: 0x10
    bus: 1
  esp_sensors:
    address: 0x20
    bus: 2
  esp_steppers:
    address: 0x08
    bus: 3