log:
  path: "./debug.log"
  mode: ["file", "stream", "journal"]
  logger: {}
  level: "DEBUG"

simulation:
  run: True
  size: 400

i2c_mapping:
  raspberry:
    address: 0x10
    bus: 2
  esp_effectors:
    address: 0x20
    bus: 1
  esp_steppers:
    address: 0x08
    bus: 1

dimension:
  robot:
    radius: 30
  map:
    width: 3000 # en mm
    height: 2000 # en mm

run:
  map_file: "configuration/map"
  speed: 0.3 # quelle unité ?
  instruction_delay: 0.5 # en secondes
  position:
    x: 0.0
    y: 0.0
    r: 0.0

serial:
  serial_port: "/dev/serial0"
  baudrate: 230400

detection:
  stop_threshold: 550 # en mm
  bypass_detection: False # permet de ne pas crash si le lidar ne fonctionne pas quand set à True
  coeff_nb_pts: 1000000000000 # 15000000

strategy:
  path:
    jaune: "configuration/strategy_jaune.yml"
    bleu: "configuration/strategy_bleu.yml"

PositionTracker:
  update_interval: 0.001

PositionController:
  speed: 0.15                     # Vitesse cible (m/s)
  rotation_speed: 0.8            # Vitesse angulaire cible (rad/s)
  acceleration: 0.0001              # Accélération cible (m/s²)
  rotation_acceleration: 0.5    # Accélération angulaire cible (rad/s²)
  update_rate: 50                # Fréquence de mise à jour en Hz
  error_pos: 0.02                # Erreur de position tolérée (m)
  error_angle: 0.05              # Erreur d'angle tolérée (rad)
